spotify/magnolify

guava/src/main/scala/magnolify/guava/semiauto/FunnelDerivation.scala

This is technically breaking but the only known downstream dependency https://github.com/spotify/scio/pull/2651 hasn't been released yet.

fix flaky FunnelDerivationSpec w.r.t. empty strings

---

cats/src/main/scala/magnolify/cats/semiauto/GroupDerivation.scala
cats/src/main/scala/magnolify/cats/semiauto/MonoidDerivation.scala
cats/src/main/scala/magnolify/cats/semiauto/SemigroupDerivation.scala
jmh/src/test/scala/magnolify/jmh/MagnolifyBench.scala

Fixes #69 #71
Before:
```
[info] Benchmark                            Mode  Cnt     Score   Error  Units
[info] CatsBench.groupCombineAll            avgt       3578.376          ns/op
[info] CatsBench.groupCombineAllOption      avgt       3223.174          ns/op
[info] CatsBench.groupCombineN              avgt        276.500          ns/op
[info] CatsBench.groupRemove                avgt        139.310          ns/op
[info] CatsBench.monoidCombineAll           avgt       2699.879          ns/op
[info] CatsBench.monoidCombineAllOption     avgt       3902.616          ns/op
[info] CatsBench.monoidCombineN             avgt        269.873          ns/op
[info] CatsBench.semigroupCombineAllOption  avgt       3635.529          ns/op
[info] CatsBench.semigroupCombineN          avgt …
```

micro-optimize cats #71

---

datastore/src/main/scala/magnolify/datastore/EntityType.scala
datastore/src/test/scala/magnolify/datastore/test/EntityTypeSpec.scala

This enables opt:ing out of the default index you get on each field, for a data heavy entity this will increase the the storage (and cost) required to keep it in datastore.

feat: Add excludeFromIndexes annotation to datastore EntityType

---

docs/avro.md
docs/bigquery.md
docs/bigtable.md
docs/datastore.md
docs/protobuf.md
docs/tensorflow.md

currently the snake case examples use hyphens which is non-custom for snake case.

change snake case examples to use underscores

---

bigtable/src/main/scala/magnolify/bigtable/BigtableType.scala
bigtable/src/test/scala/magnolify/bigtable/test/BigtableTypeSuite.scala

We have a use case when we need to read/write a case class with `java.lang.UUID` field from/to a BT table. The PR adds support for this type. It is better to store UUID in bytes representation, because it consumes less space than in its string form.

Support for java.lang.UUID for Bigtable type

---

parquet/src/main/scala/magnolify/parquet/ParquetType.scala
parquet/src/main/scala/magnolify/parquet/Schema.scala
parquet/src/test/scala/magnolify/parquet/test/ProjectionPredicateSuite.scala
parquet/src/test/scala/magnolify/parquet/test/SchemaEvolutionSuite.scala

The PR adds support for backward compatible change of a field repetition from `required` to `optional`. The case is supported by Avro according to [docs](https://avro.apache.org/docs/current/spec.html): 
```
if reader's is a union, but writer's is not:
The first schema in the reader's union that matches the writer's schema is recursively resolved against it. If none match, an error is signalled.
```
It is also supported by Parquet itself bc `optional` always able to parse `required` bc it is always there. I added a bunch of tests + tested in my own sandbox and didn't find any issues with that.
This is needed to support a reader schema that has a field with repetition changed from `required` to `optional`. The change itself is fully supported by Avro and the Parquet itself if backward …

Add support for required->optional backward compatibility

---

shared/src/main/scala/magnolify/shared/EnumType.scala
test/src/test/scala/magnolify/shared/EnumTypeSuite.scala
test/src/test/scala/magnolify/test/ADT.scala

This PR fixes a problem with serializing an instance of `ParqueType` with `EnumType` derived from a `sealed abstract class` without a no-arg constructor e.g.:
```scala
sealed abstract class Person(val entryName: String)
case object Aldrin extends Person("Aldrin")
case object Neil extends Person("Neil")
``` 
The derived `ParquetType` for this enum would fail serialization with the following error:
```
val et = ensureSerializable(implicitly[EnumType[ADT.Person]])
java.io.InvalidClassException: magnolify.test.ADT$Aldrin$; no valid constructor
at java.io.ObjectStreamClass$ExceptionInfo.newInvalidClassException(ObjectStreamClass.java:169)
at java.io.ObjectStreamClass.checkDeserialize(ObjectStreamClass.java:874)
at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2043)
at …
```

EnumType: get rid of enum instances serialization

---

project/build.properties

This commit bumps SBT to version 1.5.6.
SBT uses log4j internally for logging. A recent vulnerability has
surfaced which allows for remote code execution. SBT 1.5.6 has
been patched to include fixes for log4j internally.

Upgrade SBT to 1.5.6

---

parquet/src/main/scala/magnolify/parquet/Schema.scala

I ran into this when mistakenly getting the case sensitivity wrong with a typed read :) this error message should hopefully make it easier for people to diagnose issues with their projection case class.
It adds an additional warning for optional fields.
Tested it out in a sample Scio job, with optional & required fields
```bash
WARNING: Requested field `Suit: OPTIONAL` is not present in written file schema and will be evaluated as `Option.empty`. Available fields are: [suit: OPTIONAL]
...
Mar 07, 2022 2:45:34 PM org.apache.beam.sdk.io.hadoop.format.HadoopFormatIO$HadoopInputFormatBoundedSource$HadoopInputFormatReader close
INFO: Closing reader after reading 4 records.
```
```bash
[error] org.apache.parquet.io.InvalidRecordException: Requested field `Suit: REQUIRED` is not present in …
```

clarify error message for missing required Parquet fields + add warning for missing optional fields

---

parquet/src/main/scala/magnolify/parquet/ParquetType.scala
parquet/src/main/scala/magnolify/parquet/Predicate.scala
parquet/src/test/scala/magnolify/parquet/test/PredicateSuite.scala
parquet/src/test/scala/magnolify/parquet/test/ProjectionPredicateSuite.scala
parquet/src/test/scala/magnolify/parquet/test/ProjectionSuite.scala

adds support for custom `FilterPredicate` generation for types `T : ParquetField.Primitive`:
```scala
Predicate.onField[Int]("i1")(_ % 2 == 0)
```
I didn't go as far as adding macro support the way @nevillelyh did in [parquet-extra](https://github.com/nevillelyh/parquet-extra/blob/main/parquet-avro/src/main/scala/me/lyh/parquet/avro/Predicate.scala)... this implementation is a little more manual, maybe macro support (i.e `Predicate[RecordT)(_.i1 % 2 == 0)`) can be implemented further down the line. But it leverages the functionality of our Parquet typeclass to do things like convert between underlying Parquet types and the Scala projected type--for example, you can filter directly on `Instant` logical type fields, rather than having to assert on the raw millisecond value.

(#500) Support FilterPredicate gen for ParquetFields

---

build.sbt
tensorflow/src/main/protobuf/path.proto
tensorflow/src/main/protobuf/schema.proto
tensorflow/src/main/scala/magnolify/tensorflow/ExampleType.scala
tensorflow/src/test/scala/magnolify/tensorflow/test/ExampleTypeSuite.scala

Closes https://github.com/spotify/magnolify/issues/485.
Derive the tf.schema from using `ExampleType`. This will allow the serialization of such schema along with the example data.

Derive tf.schema in ExampleType

---

avro/src/main/scala/magnolify/avro/AvroType.scala

This PR aims to improve the derived typeclass performance for Avro
Results of `jmh` benchmarks with `jmh/jmh:run -i 20 -wi 10 -f1 -t1 magnolify.jmh.AvroBench` are ~actually not~ looking good
| branch | `avroTo` | `avroFrom` | `avroSchema` |
|-----------|------------|-----------------|---------------------|
| ~PR~       |  ~8981.511 ns/op~  | ~6675.408 ns/op~ | ~3.697 ns/op~ |
| PR       |  3967.037 ns/op  | 1718.793 ns/op | 4.016 ns/op |
| main    |  8075.481 ns/op  | 3190.532 ns/op | 3.832 ns/op |
| v0.4.8  |  9463.751 ns/op  | 3417.335 ns/op | 3.767 ns/op |
Looks like `rawConstruct` is making an extra call to `MagnoliaUtil.checkParamLengths` wich is worse that going though the field map in the schema
Edit: Using vars instead improves greatly avro conversion performances (~ 40% to 50% …

AvroType performace improvements

---

bigquery/src/main/scala/magnolify/bigquery/TableRowType.scala
jmh/src/test/scala/magnolify/jmh/MagnolifyBench.scala
parquet/src/main/scala/magnolify/parquet/ParquetType.scala
protobuf/src/main/scala/magnolify/protobuf/ProtobufType.scala
tensorflow/src/main/scala/magnolify/tensorflow/ExampleType.scala

Bring `TableRow` structure similar to `AvroType` in #548 
- No need to fallback to string schemas. Rely on clone (this is a deep copy) to construct schemas
- Use of `set` instead of `put`:
> Sets the given field value (may be null) for the given field name. Any existing value for the field will be overwritten. It may be more slightly more efficient than put(String, Object) because it avoids accessing the field's original value.
jmh perf test are similar between versions.
Caching the schema in `ParquetType`
Fixing schema cache in `ExampleType`

Streamline with AvroType

---

tensorflow/src/test/scala/magnolify/tensorflow/test/ExampleTypeSuite.scala

Relates to #557 
On `v0.4.8` with test like
```scala
ef.schema("first")
assertEquals(ef.schema("second")(CaseMapper.identity), expectedFieldSchema)
```
it would fail with
```diff
=> Diff (- obtained, + expected)
feature {
-  name: "first.b"
+  name: "b"
type: INT
feature {
-  name: "first.i"
+  name: "i"
type: INT
```
`ExampleField` schema was caching the 1st parent key.
Ensured that the field `schema` does not contain cached values from wrapping class

Add testing for tensorflow cached field schema

---

avro/src/main/scala/magnolify/avro/AvroType.scala
avro/src/test/scala/magnolify/avro/test/AvroTypeSuite.scala
bigquery/src/main/scala/magnolify/bigquery/TableRowType.scala
bigquery/src/test/scala/magnolify/bigquery/test/TableRowTypeSuite.scala
bigtable/src/main/scala/magnolify/bigtable/BigtableType.scala
bigtable/src/test/scala/magnolify/bigtable/test/BigtableTypeSuite.scala
datastore/src/main/scala/magnolify/datastore/EntityType.scala
datastore/src/test/scala/magnolify/datastore/test/EntityTypeSuite.scala
guava/src/main/scala/magnolify/guava/semiauto/FunnelDerivation.scala
guava/src/test/scala/magnolify/guava/test/FunnelDerivationSuite.scala
neo4j/src/main/scala/magnolify/neo4j/ValueType.scala
neo4j/src/test/scala/magnolify/neo4j/ValueTypeSuite.scala
parquet/src/main/scala/magnolify/parquet/ParquetType.scala
parquet/src/main/scala/magnolify/parquet/unsafe/package.scala
parquet/src/test/scala/magnolify/parquet/test/ParquetTypeSuite.scala
protobuf/src/main/scala/magnolify/protobuf/ProtobufType.scala
protobuf/src/main/scala/magnolify/protobuf/unsafe/package.scala
protobuf/src/test/scala/magnolify/protobuf/test/ProtobufTypeSuite.scala
shared/src/main/scala/magnolify/shared/Converter.scala
tensorflow/src/main/scala/magnolify/tensorflow/ExampleType.scala
tensorflow/src/test/scala/magnolify/tensorflow/test/ExampleTypeSuite.scala
test/src/test/scala/magnolify/test/Simple.scala

The new Neo4J support works well, but value classes generate inner properties in Neo4J, when we would like them to be just strongly typed values.

Treat value classes as such

---

avro/src/main/scala/magnolify/avro/AvroType.scala
avro/src/main/scala/magnolify/avro/package.scala
build.sbt
docs/parquet.md
parquet/src/main/scala/magnolify/parquet/ParquetField.scala
parquet/src/main/scala/magnolify/parquet/ParquetType.scala
parquet/src/main/scala/magnolify/parquet/SchemaUtil.scala
parquet/src/test/scala/magnolify/parquet/test/AvroParquetSuite.scala
parquet/src/test/scala/magnolify/parquet/test/ParquetTypeSuite.scala
parquet/src/test/scala/magnolify/parquet/test/SchemaUtilSuite.scala
parquet/src/test/scala/magnolify/parquet/test/util/AvroSchemaComparer.scala
shared/src/main/scala/magnolify/shared/doc.scala

What is done:
- Added a way to annotate case classes and fields in order to add extra metadata to parquet files
- Annotations are collected in `ParquetType[T]`'s members `fieldAnnotations: Map[String, String]` and  `typeAnnotation: Option[String]` that contain respectively 1) the top level and nested fields annotations 2) the top level class annotation
- ParquetField class was moved to a dedicated file
What is left:
- Add annotations to a parquet file on write using an approach that is yet to be finalized

Typed Parquet Annotations

---

parquet/src/main/scala/magnolify/parquet/ParquetType.scala
parquet/src/test/scala/magnolify/parquet/AvroParquetSuite.scala
parquet/src/test/scala/magnolify/parquet/ParquetTypeSuite.scala

There were some issues downstream in Scio because `ParquetType` couldn't be serialized as part of a `PTransform`.
Added `@transient` -- this matches the pattern we use elsewhere in Magnolify like [AvroType](https://github.com/spotify/magnolify/blob/main/avro/src/main/scala/magnolify/avro/AvroType.scala#L50), ExampleType, TableRowType etc :)

Make schema val @transient in ParquetType

---

bigquery/src/main/scala/magnolify/bigquery/TableRowType.scala
bigquery/src/test/scala/magnolify/bigquery/TableRowTypeSuite.scala
test/src/test/scala/magnolify/test/Simple.scala

This will help using projection for BQ on the [TableReadOptions.addAllSelectedFields](https://cloud.google.com/java/docs/reference/google-cloud-bigquerystorage/latest/com.google.cloud.bigquery.storage.v1beta1.ReadOptions.TableReadOptions.Builder#com_google_cloud_bigquery_storage_v1beta1_ReadOptions_TableReadOptions_Builder_addAllSelectedFields_java_lang_Iterable_java_lang_String__)

Add BQ selectedFields to TableRowType

---

avro/src/main/scala/magnolify/avro/AvroType.scala
avro/src/main/scala/magnolify/avro/logical/package.scala
avro/src/test/scala/magnolify/avro/AvroTypeSuite.scala
cats/src/test/scala/magnolify/cats/TestEq.scala
parquet/src/test/scala/magnolify/parquet/AvroParquetSuite.scala
scalacheck/src/test/scala/magnolify/scalacheck/TestArbitrary.scala
tools/src/main/scala/magnolify/tools/AvroParser.scala
tools/src/main/scala/magnolify/tools/Schema.scala
tools/src/test/scala/magnolify/tools/AvroParserSuite.scala
tools/src/test/scala/magnolify/tools/SchemaPrinterSuite.scala

scala/java `String` will be represented in with the `"avro.java.string": "String"` property in the avro schema.
Logical types baked by avro string should be created using the `CharSequence` type as the property is forbidden there (exception is thrown when building the schema)

Force avro String type in generated schema

---

guava/src/main/scala/magnolify/guava/semiauto/FunnelDerivation.scala
guava/src/test/scala/magnolify/guava/FunnelDerivationSuite.scala

As per the warning on [PrimitiveSink.putString](https://javadoc.io/doc/com.google.guava/guava/latest/com/google/common/hash/PrimitiveSink.html#putString(java.lang.CharSequence,java.nio.charset.Charset)) JavaDoc:
> Warning: This method, which reencodes the input before processing it, is useful only for cross-language compatibility. For other use cases, prefer putUnencodedChars(java.lang.CharSequence), which is faster, produces the same output across Java releases, and processes every char in the input, even if some are invalid.
Or maybe leave this out and let people make their own decision as to what they want for the `Funnel[String]` instance?

Use `putUnencodedChars` for Funneling strings.

---

parquet/src/main/scala/magnolify/parquet/ParquetField.scala
parquet/src/main/scala/magnolify/parquet/ParquetType.scala
parquet/src/test/scala/magnolify/parquet/AvroParquetSuite.scala
parquet/src/test/scala/magnolify/parquet/ParquetTypeSuite.scala

case mapper was not applied when creating the doc fields.
When generating the `avroSchema` for a `ParquetField`, docs were not found as there is a mismatch between field names.

Respect case mapper for field documentation in parquet avro schema

---

guava/src/main/scala/magnolify/guava/auto/package.scala
guava/src/test/scala/magnolify/guava/FunnelDerivationSuite.scala
refined/src/test/scala/magnolify/refined/RefinedSuite.scala

`FunelDerivation` has an alias in the `auto` package, which is not in line with other semi-auto typeclasses.
When both `auto` and `semiauto` are imported, this raises a warning for shadowing.
Force user to import `FunelDerivation` from the `semiauto` package

Remove FunelDerivation alias

---

docs/avro.md

I found a typo in reading `avro.md` in docs.
```diff
< Achiving backward compatibility when
> Achieving backward compatibility when
```

fix typo: achiving -> achieving

---

docs/protobuf.md
protobuf/src/main/scala/magnolify/protobuf/ProtobufType.scala
protobuf/src/main/scala/magnolify/protobuf/unsafe/package.scala
protobuf/src/test/protobuf/Proto3.proto
protobuf/src/test/scala/magnolify/protobuf/ProtobufTypeSuite.scala
refined/src/test/scala/magnolify/refined/RefinedSuite.scala

Since [protobuf 3.15.0](https://github.com/protocolbuffers/protobuf/releases/tag/v3.15.0) (2021-02), `optional` is supported by default in the proto 3 syntax.
Adapt the `ProtobufType` typeclass to take this into account.
As side effect, this removes the need to check for proto 2 syntax.
Fix #814

Support proto3 optional

---

shared/src/main/scala-3/magnolify/shared/AnnotationTypeMacros.scala
shared/src/main/scala-3/magnolify/shared/EnumTypeMacros.scala
test/src/test/scala/magnolify/shared/EnumTypeSuite.scala

While this library cross-builds with scala 2, it is better to keep consistency and only use implicit.

Keep using implicit while cross compiling with scala 2

---

parquet/src/main/scala/magnolify/parquet/ParquetField.scala
parquet/src/test/scala/magnolify/parquet/ParquetTypeSuite.scala
tools/src/main/scala/magnolify/tools/AvroParser.scala
tools/src/main/scala/magnolify/tools/BigQueryParser.scala
tools/src/main/scala/magnolify/tools/ParquetParser.scala
tools/src/main/scala/magnolify/tools/Schema.scala
tools/src/main/scala/magnolify/tools/SchemaPrinter.scala
tools/src/test/scala/magnolify/tools/AvroParserSuite.scala
tools/src/test/scala/magnolify/tools/BigQueryParserSuite.scala
tools/src/test/scala/magnolify/tools/ParquetParserSuite.scala
tools/src/test/scala/magnolify/tools/SchemaPrinterSuite.scala

Implementing `Map[K, V]` as described by parquet MAP logical type [documentation](https://github.com/apache/parquet-format/blob/master/LogicalTypes.md#maps)

Parquet map logical type

---

.github/workflows/ci.yml
build.sbt

With #887, scala 3 artifacts are still published by `+publish`. Change strategy to keep scala 3 build in CI, only skip publishing

Keep scala 3 build but skip publish

---

.github/workflows/scalafix.yaml
.gitignore
scalafix/.sbtopts
scalafix/build.sbt
scalafix/input-0_7/src/main/scala/fix/MapBasedConverters.scala
scalafix/output-0_7/src/main/scala/fix/MapBasedConverters.scala
scalafix/project/ConfigAxis.scala
scalafix/project/build.properties
scalafix/project/plugins.sbt
scalafix/rules/src/main/resources/META-INF/services/scalafix.v1.Rule
scalafix/rules/src/main/scala/fix/MapBasedConverters.scala
scalafix/tests/src/test/scala/fix/RuleSuite.scala

#847 changed underlying `Converte#from/to` types.
Update user relying on those to move to `ExampleType.apply` instead

Add scalafix 0.7 migration rule

---

protobuf/src/test/protobuf/Proto2.proto
protobuf/src/test/protobuf/Proto3.proto
shared/src/main/scala-2.12/magnolify/shims/SerializableCanBuildFrom.scala
test/src/test/scala/magnolify/test/Simple.scala

Set could be use as collection in scala 2.13 but not in 2.12 due to a missing serializable can build from factory.

[shared] Add scala 2.12 CanBuildFrom for Set

---

.scala-steward.conf

As library, this should stay on the LTS line

[scala-steward] Stay on scala3 LTS line

---

.github/workflows/ci.yml
build.sbt

Codecov coverage report changed to a github action.
See https://about.codecov.io/blog/january-product-update-updating-the-codecov-ci-uploaders-to-the-codecov-cli/

(chore) Update to codecov-action

---

build.sbt

Add `sl4j-simple` as logger implementation, fork tests and pass java options to log into `target/magnolify.log` at `info` level

chore: configure slf4j-simple as test logger
